export * from './auth.controller';
export * from './user.controller';
export * from './badge.controller';
export * from './challenge.controller';
export * from './exerciseType.controller';
export * from './exerciseChallenge.controller';
export * from './userBadge.controller';
export * from './userChallenge.controller';
export * from './salle.controller';